/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated.word.lambda.api;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void findRepeat() {
        String testThis = "Here's a string. It has a repeated word";

        assertEquals("a", Library.findRepeat(testThis));
    }
}
