/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated.word.lambda.api;

import java.util.Hashtable;

public class Library {

    public static String findRepeat(String inputString) {
        String[] inputArr = inputString.split(" ");

        Hashtable wordsTable = new Hashtable();

        for (int i = 0; i < inputArr.length; i++) {
            if (wordsTable.containsKey(inputArr[i])) {
                return inputArr[i];
            } else {
                wordsTable.put(inputArr[i], 1);
            }
        }
        return null;
    }
}
